# backend/dummy_data.py
doctors = [
    {
        "id": 1,
        "name": "Dr. Ahmed Khan",
        "specialty": "Cardiologist",
        "sub_specialties": ["Interventional Cardiology", "Heart Failure", "Echocardiography"],
        "city": "Rawalpindi",
        "experience_years": 12,
        "fee": 2000,
        "rating": 4.8,
        "total_reviews": 342,
        "available": True,
        "hospital": "Shifa International Hospital",
        "qualification": "FCPS (Cardiology), MRCP (UK)",
        "university": "King Edward Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["chest pain", "heart disease", "blood pressure", "breathing problems", "heart attack", "palpitations", "arrhythmia"],
        "availability_slots": ["10:00 AM", "11:00 AM", "2:00 PM", "3:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 2,
        "name": "Dr. Fatima Zaidi",
        "specialty": "Cardiologist",
        "sub_specialties": ["Pediatric Cardiology", "Congenital Heart Disease"],
        "city": "Islamabad",
        "experience_years": 18,
        "fee": 3500,
        "rating": 4.9,
        "total_reviews": 567,
        "available": True,
        "hospital": "Pakistan Institute of Medical Sciences",
        "qualification": "FSCAI, FACC (USA), FCPS",
        "university": "Dow University of Health Sciences",
        "languages": ["English", "Urdu", "Sindhi"],
        "treats": ["chest pain", "heart disease", "blood pressure", "breathing problems", "heart attack", "congenital heart defects"],
        "availability_slots": ["9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "3:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 3,
        "name": "Dr. Sara Ali",
        "specialty": "Dermatologist",
        "sub_specialties": ["Cosmetic Dermatology", "Laser Treatment", "Pediatric Dermatology"],
        "city": "Islamabad",
        "experience_years": 8,
        "fee": 1500,
        "rating": 4.5,
        "total_reviews": 234,
        "available": True,
        "hospital": "PIMS Hospital",
        "qualification": "FCPS (Dermatology), Diploma in Aesthetic Medicine",
        "university": "Quaid-e-Azam University",
        "languages": ["English", "Urdu"],
        "treats": ["skin rash", "acne", "eczema", "hair loss", "allergy", "skin infection", "psoriasis", "vitiligo"],
        "availability_slots": ["11:00 AM", "1:00 PM", "2:00 PM", "4:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 4,
        "name": "Dr. Imran Chaudhry",
        "specialty": "Dermatologist",
        "sub_specialties": ["Dermatosurgery", "Mohs Surgery", "Skin Cancer"],
        "city": "Rawalpindi",
        "experience_years": 15,
        "fee": 2500,
        "rating": 4.7,
        "total_reviews": 412,
        "available": True,
        "hospital": "CMH Rawalpindi",
        "qualification": "MRCP (Dermatology), FCPS",
        "university": "Army Medical College",
        "languages": ["English", "Urdu", "Punjabi", "Pashto"],
        "treats": ["skin rash", "acne", "eczema", "hair loss", "allergy", "skin cancer", "moles", "scar treatment"],
        "availability_slots": ["10:00 AM", "12:00 PM", "2:00 PM", "3:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 5,
        "name": "Dr. Usman Malik",
        "specialty": "General Physician",
        "sub_specialties": ["Internal Medicine", "Preventive Healthcare"],
        "city": "Rawalpindi",
        "experience_years": 15,
        "fee": 1000,
        "rating": 4.6,
        "total_reviews": 678,
        "available": True,
        "hospital": "Holy Family Hospital",
        "qualification": "MBBS, FCPS (Internal Medicine)",
        "university": "Rawalpindi Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["fever", "flu", "cough", "general checkup", "weakness", "headache", "body aches", "dizziness"],
        "availability_slots": ["9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "4:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 6,
        "name": "Dr. Hina Tariq",
        "specialty": "General Physician",
        "sub_specialties": ["Geriatric Medicine", "Palliative Care"],
        "city": "Islamabad",
        "experience_years": 10,
        "fee": 1200,
        "rating": 4.7,
        "total_reviews": 289,
        "available": True,
        "hospital": "Shifa International Hospital",
        "qualification": "MBBS, MRCP (UK)",
        "university": "Fatima Jinnah Medical University",
        "languages": ["English", "Urdu"],
        "treats": ["fever", "flu", "cough", "general checkup", "weakness", "headache", "elderly care", "chronic disease"],
        "availability_slots": ["10:00 AM", "1:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 7,
        "name": "Dr. Ayesha Tariq",
        "specialty": "Gynecologist",
        "sub_specialties": ["High Risk Pregnancy", "Infertility", "Laparoscopic Surgery"],
        "city": "Islamabad",
        "experience_years": 10,
        "fee": 2500,
        "rating": 4.9,
        "total_reviews": 823,
        "available": True,
        "hospital": "Quaid-e-Azam International Hospital",
        "qualification": "FCPS (Obstetrics & Gynecology), MRCOG (UK)",
        "university": "King Edward Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["pregnancy", "women health", "period problems", "fertility", "hormonal issues", "PCOS", "menopause"],
        "availability_slots": ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 8,
        "name": "Dr. Nida Khan",
        "specialty": "Gynecologist",
        "sub_specialties": ["Reproductive Medicine", "IVF Specialist"],
        "city": "Rawalpindi",
        "experience_years": 14,
        "fee": 3000,
        "rating": 4.8,
        "total_reviews": 456,
        "available": True,
        "hospital": "Al Nafees Medical Center",
        "qualification": "FRCOG (London), FCPS",
        "university": "Quaid-e-Azam University",
        "languages": ["English", "Urdu", "Punjabi", "Arabic"],
        "treats": ["pregnancy", "women health", "period problems", "fertility", "IVF", "hormonal issues", "endometriosis"],
        "availability_slots": ["10:00 AM", "12:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 9,
        "name": "Dr. Bilal Hussain",
        "specialty": "Orthopedic Surgeon",
        "sub_specialties": ["Sports Medicine", "Joint Replacement", "Arthroscopy"],
        "city": "Rawalpindi",
        "experience_years": 14,
        "fee": 3000,
        "rating": 4.7,
        "total_reviews": 345,
        "available": True,
        "hospital": "CMH Rawalpindi",
        "qualification": "FRCS (Orthopedics), FCPS",
        "university": "Army Medical College",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["bone pain", "joint pain", "back pain", "knee pain", "fracture", "spine", "arthritis", "sports injury"],
        "availability_slots": ["9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 10,
        "name": "Dr. Asad Mehmood",
        "specialty": "Orthopedic Surgeon",
        "sub_specialties": ["Pediatric Orthopedics", "Spine Surgery"],
        "city": "Islamabad",
        "experience_years": 20,
        "fee": 4000,
        "rating": 4.9,
        "total_reviews": 789,
        "available": True,
        "hospital": "Pakistan Institute of Medical Sciences",
        "qualification": "FRCS (Edinburgh), FCPS, FACS",
        "university": "Dow University of Health Sciences",
        "languages": ["English", "Urdu", "Sindhi"],
        "treats": ["bone pain", "joint pain", "back pain", "knee pain", "fracture", "spine", "scoliosis", "cerebral palsy"],
        "availability_slots": ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 11,
        "name": "Dr. Farah Naz",
        "specialty": "Pediatrician",
        "sub_specialties": ["Neonatology", "Pediatric Emergency"],
        "city": "Islamabad",
        "experience_years": 9,
        "fee": 1500,
        "rating": 4.8,
        "total_reviews": 456,
        "available": True,
        "hospital": "Children Hospital Islamabad",
        "qualification": "FCPS (Pediatrics), MRCPCH (UK)",
        "university": "Rawalpindi Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["child fever", "baby health", "vaccination", "child growth", "newborn care", "developmental delay"],
        "availability_slots": ["9:00 AM", "10:00 AM", "11:00 AM", "2:00 PM", "3:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 12,
        "name": "Dr. Omar Sheikh",
        "specialty": "Pediatrician",
        "sub_specialties": ["Pediatric Cardiology", "Pediatric Intensive Care"],
        "city": "Rawalpindi",
        "experience_years": 16,
        "fee": 2500,
        "rating": 4.9,
        "total_reviews": 623,
        "available": True,
        "hospital": "Holy Family Hospital",
        "qualification": "FRCPCH (London), FCPS",
        "university": "King Edward Medical University",
        "languages": ["English", "Urdu"],
        "treats": ["child fever", "baby health", "vaccination", "child growth", "newborn care", "child heart disease"],
        "availability_slots": ["11:00 AM", "1:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 13,
        "name": "Dr. Kamran Sheikh",
        "specialty": "Neurologist",
        "sub_specialties": ["Stroke Neurology", "Epilepsy", "Movement Disorders"],
        "city": "Rawalpindi",
        "experience_years": 18,
        "fee": 3500,
        "rating": 4.9,
        "total_reviews": 534,
        "available": True,
        "hospital": "Benazir Bhutto Hospital",
        "qualification": "FRCP (Neurology), FCPS",
        "university": "Army Medical College",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["headache", "migraine", "epilepsy", "memory loss", "stroke", "nerve pain", "parkinsons", "multiple sclerosis"],
        "availability_slots": ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 14,
        "name": "Dr. Rabia Anwar",
        "specialty": "Neurologist",
        "sub_specialties": ["Neurophysiology", "Sleep Medicine"],
        "city": "Islamabad",
        "experience_years": 12,
        "fee": 3000,
        "rating": 4.7,
        "total_reviews": 345,
        "available": True,
        "hospital": "Shifa International Hospital",
        "qualification": "MRCP (Neurology), FCPS",
        "university": "Quaid-e-Azam University",
        "languages": ["English", "Urdu"],
        "treats": ["headache", "migraine", "epilepsy", "memory loss", "nerve pain", "sleep disorders"],
        "availability_slots": ["10:00 AM", "12:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 15,
        "name": "Dr. Sana Mirza",
        "specialty": "Psychiatrist",
        "sub_specialties": ["Child Psychiatry", "Addiction Psychiatry", "Geriatric Psychiatry"],
        "city": "Islamabad",
        "experience_years": 11,
        "fee": 3000,
        "rating": 4.7,
        "total_reviews": 289,
        "available": True,
        "hospital": "Fountain House Islamabad",
        "qualification": "FCPS (Psychiatry), MRCPsych (UK)",
        "university": "Fatima Jinnah Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["anxiety", "depression", "stress", "insomnia", "mental health", "panic attacks", "OCD", "bipolar disorder"],
        "availability_slots": ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 16,
        "name": "Dr. Javed Iqbal",
        "specialty": "Psychiatrist",
        "sub_specialties": ["Forensic Psychiatry", "Neuropsychiatry"],
        "city": "Rawalpindi",
        "experience_years": 22,
        "fee": 4000,
        "rating": 4.8,
        "total_reviews": 678,
        "available": True,
        "hospital": "CMH Rawalpindi",
        "qualification": "FRCPsych (London), FCPS",
        "university": "King Edward Medical University",
        "languages": ["English", "Urdu", "Punjabi", "Pashto"],
        "treats": ["anxiety", "depression", "stress", "insomnia", "mental health", "panic attacks", "psychosis"],
        "availability_slots": ["9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 17,
        "name": "Dr. Tariq Mehmood",
        "specialty": "ENT Specialist",
        "sub_specialties": ["Otology", "Rhinology", "Head & Neck Surgery"],
        "city": "Rawalpindi",
        "experience_years": 13,
        "fee": 2000,
        "rating": 4.6,
        "total_reviews": 412,
        "available": True,
        "hospital": "District Headquarter Hospital",
        "qualification": "FCPS (ENT), MRCS (UK)",
        "university": "Rawalpindi Medical University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["ear pain", "hearing loss", "sore throat", "tonsils", "nose bleeding", "sinus", "vertigo", "voice problems"],
        "availability_slots": ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 18,
        "name": "Dr. Shumaila Akhtar",
        "specialty": "ENT Specialist",
        "sub_specialties": ["Pediatric ENT", "Laryngology"],
        "city": "Islamabad",
        "experience_years": 9,
        "fee": 1800,
        "rating": 4.7,
        "total_reviews": 256,
        "available": True,
        "hospital": "Pakistan Institute of Medical Sciences",
        "qualification": "FCPS (ENT), DOHNS (UK)",
        "university": "Quaid-e-Azam University",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["ear pain", "hearing loss", "sore throat", "tonsils", "nose bleeding", "sinus", "cough", "snoring"],
        "availability_slots": ["9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 19,
        "name": "Dr. Nadia Iqbal",
        "specialty": "Diabetologist",
        "sub_specialties": ["Pediatric Diabetes", "Gestational Diabetes", "Thyroid Disorders"],
        "city": "Islamabad",
        "experience_years": 16,
        "fee": 2500,
        "rating": 4.8,
        "total_reviews": 534,
        "available": True,
        "hospital": "Pakistan Institute of Medical Sciences",
        "qualification": "MRCP (Endocrinology), FCPS",
        "university": "King Edward Medical University",
        "languages": ["English", "Urdu"],
        "treats": ["diabetes", "sugar", "insulin", "blood sugar", "thyroid", "hormones", "obesity", "metabolic syndrome"],
        "availability_slots": ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"],
        "off_days": ["Sunday"]
    },
    {
        "id": 20,
        "name": "Dr. Haroon Rashid",
        "specialty": "Diabetologist",
        "sub_specialties": ["Diabetic Foot", "Insulin Pump Therapy"],
        "city": "Rawalpindi",
        "experience_years": 11,
        "fee": 2000,
        "rating": 4.6,
        "total_reviews": 345,
        "available": True,
        "hospital": "Shifa International Hospital",
        "qualification": "FCPS (Endocrinology), CDE",
        "university": "Army Medical College",
        "languages": ["English", "Urdu", "Punjabi"],
        "treats": ["diabetes", "sugar", "insulin", "blood sugar", "thyroid", "diabetic foot", "neuropathy"],
        "availability_slots": ["10:00 AM", "12:00 PM", "3:00 PM", "5:00 PM"],
        "off_days": ["Sunday"]
    },
]

specialties_list = [
    "Cardiologist", "Dermatologist", "General Physician", "Gynecologist",
    "Orthopedic Surgeon", "Pediatrician", "Neurologist", "Psychiatrist",
    "ENT Specialist", "Diabetologist"
]

symptom_to_specialty = {
    "chest pain": "Cardiologist", "heart": "Cardiologist", "blood pressure": "Cardiologist",
    "heart attack": "Cardiologist", "palpitations": "Cardiologist",
    "skin": "Dermatologist", "acne": "Dermatologist", "rash": "Dermatologist",
    "hair loss": "Dermatologist", "eczema": "Dermatologist",
    "fever": "General Physician", "flu": "General Physician", "cough": "General Physician",
    "headache": "General Physician", "weakness": "General Physician",
    "pregnancy": "Gynecologist", "period": "Gynecologist", "women": "Gynecologist",
    "fertility": "Gynecologist",
    "bone": "Orthopedic Surgeon", "joint": "Orthopedic Surgeon", "knee": "Orthopedic Surgeon",
    "back pain": "Orthopedic Surgeon", "fracture": "Orthopedic Surgeon",
    "child": "Pediatrician", "baby": "Pediatrician", "vaccination": "Pediatrician",
    "migraine": "Neurologist", "epilepsy": "Neurologist", "memory": "Neurologist",
    "nerve": "Neurologist",
    "anxiety": "Psychiatrist", "depression": "Psychiatrist", "stress": "Psychiatrist",
    "insomnia": "Psychiatrist",
    "ear": "ENT Specialist", "throat": "ENT Specialist", "nose": "ENT Specialist",
    "sinus": "ENT Specialist", "hearing": "ENT Specialist",
    "diabetes": "Diabetologist", "sugar": "Diabetologist", "insulin": "Diabetologist",
    "thyroid": "Diabetologist",
    "breathing": "Pulmonologist", "asthma": "Pulmonologist", "lung": "Pulmonologist",
}

print(f"✅ Loaded {len(doctors)} doctors")